### ISSUE TITLE
Missing functions?

### ISSUE THREAD

**Issue by baeng72** [Tucchhaa/gl-engine#1]
I'm working through the code, and I think it's quite well done.

There appear to be a few missing functions.

In renderer.cpp, there's a call to Hierarchy::getTransform() used several times, but there is not static getTransform() defined in the Hierarchy class. Looking at other functions in Hierarchy (updateTransform()), I guess it gets the gameObject::transform value in some way.

In the irender class, there's no setScene() function, but in renderer.cpp, there's a call to IRenderer::setScene(), which I assume is something like:
void IRenderer::setScene(Scene * scene){ currentScene = scene; }

**Comment by Tucchhaa** [comment]
Hi!

renderer.cpp is a bit obsolete file. I used renderer.cpp to implement forward rendering, but then I switched to deferred rendering and I haven't updated the forward renderer.

You can try to change `Hierarchy::getTransform(object)` to `object->transform`. 

For setScene, take a look at [DeferredRenderer::afterSceneSetup](https://github.com/Tucchhaa/gl-engine/blob/main/apis/opengl/deferred-renderer.cpp#L265C8-L265C43). Basically these two functions do the same thing.

Please, let me know if it helps. If you have any questions, I'm happy to help you :)

**Comment by baeng72** [comment]
Thanks for the reply!
If I were a smarter person, which clearly I'm not, I'd have looked in
sourceFiles.cmake and seen the renderer.cpp was not part of the build. :)
I'm working my way through your code,.
I know some things about graphics techniques, but struggle when making an
engine, so I like checking out how other coders setup scenes and materials
in an engine.
You can checkout my github if you want to see some Vulkan stuff.
Thanks for sharing your code!
